version: 2.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
          filters:
            branches:
              only: main     

jobs:
  test:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${PROJECT_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Generate Docker Tag
          command: |
            echo "export DOCKER_TAG=${CIRCLE_SHA1:0:7}" >> $BASH_ENV
            source $BASH_ENV
            echo $DOCKER_TAG
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
            docker push $DOCKER_IMAGE:$DOCKER_TAG
 
      - run:
          name: Clone K8s Manifests Repo
          command: |
            git clone https://x-access-token:$MANIFEST_REPO_PAT@$K8S_MANIFEST_REPO k8s-manifests
            cd k8s-manifests
            git config user.name "CircleCI"
            git config user.email "circleci@example.com"
      - run:
          name: Update Kubernetes Manifests
          command: |
            cd k8s-manifests
            git pull origin main
            awk -v image="${DOCKER_IMAGE}:${DOCKER_TAG}" '
              /image:/ {$0 = "        image: " image}
              {print}
            ' k8s/app.yml > temp.yml && mv temp.yml k8s/app.yml
            if [[ -n $(git status -s) ]]; then
              echo "Changes detected. Committing and pushing..."
              git add .
              git commit -m "Update image tag to ${DOCKER_TAG}"
              git push origin main
            else
              echo "No changes detected in Kubernetes manifests."
            fi